apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redbutton-websocket-poc
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`redbutton.online`)
      services:
        - kind: Service
          name: redbutton-websocket-poc
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: redbutton-websocket-poc
  labels:
    app: redbutton-websocket-poc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: redbutton-websocket-poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbutton-websocket-poc
  labels:
    app: redbutton-websocket-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redbutton-websocket-poc
  template:
    metadata:
      labels:
        app: redbutton-websocket-poc
    spec:
      containers:
        - name: redbutton-websocket-poc
          image: marcinbablok/redbutton-websocket-poc:latest
          ports:
            - containerPort: 8080
              name: http



